### ISSUE TITLE
[Release] v0.8.0

### ISSUE THREAD

**Issue by snamiki1212** [snamiki1212/plangoab#69]
from: https://github.com/snamiki1212/plangoab/issues/8#issuecomment-817067495

---

- [x] #70 Fix to HowToUse modal more to see easy, especially size is wired. 
- [x] #70 Add Collaboration Companies section on somewhere like footer and README
- [x] #71 Enable screen shot
- [x] #76 Add both resource and event before and after
